### ISSUE TITLE
Setup database seed

### ISSUE THREAD

**Issue by alallema** [louije/court-message#103]
## Descriptions:
The purpose of seed data is to bootstrap your database. It's allow us to have data ready for testing, but also to have admin accounts ready for application execution and enable us to test that all our models are working correctly.

## Todo:
- [x] Create seed file
- [ ] Add seed command `rails db:seed` to startup during testing
- [ ] Adapt test for testing with seed

## Notes:

The seed file should contain:
- At least one admin of each type (super_admin, site_admin, team_admin)
- At least 2 users
- At least 2 teams
- At least 1 conversation with 2 or more messages acessible by only 1 user.
- At least 1 conversation with 2 or more messages accessible by more than 1 user
